name: lint test build
on: push
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Get code
            uses: actions/checkout@v3
          - name: Install node
            uses: actions/setup-node@v3
            with:
              node-version: 18
          - name: Install dependencies
            run: npm install
          - name: lint
            run: npm run lint
          - name: test
            run: npm test
          - name: build
            run: npm run build
          - name: finish
            run: echo "SUCCESS WORKFLOW"
